name: home_widget_counter
description: "A new Flutter project."
publish_to: 'none'

version: 7.0.0+130

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  home_widget:
    git:
      url: https://github.com/ReptileStyle/home_widget.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/dash_sign_small.png